### ISSUE TITLE
LM-G710 Connection and multiple errors

### ISSUE THREAD

**Issue by phodina** [steadfasterX/SALT#38]
Hi,
I've connected the `LM-G710` (LG G7 ThinQ) SDM845 based device under the download mode and it somehow connected but there were multiple errors and in the end the feature for full backup did not work and threw more errors.

![SALT_Full_Backup](https://github.com/steadfasterX/SALT/assets/2997905/16f4e383-dd85-4214-a1e2-33d8be24d094)
![SALT_LM-G710TM](https://github.com/steadfasterX/SALT/assets/2997905/06bf6d61-67ee-42da-bca6-13105ca13916)
[salt.log](https://github.com/steadfasterX/SALT/files/12342100/salt.log)

**Comment by phodina** [comment]
There is no requirement that mentions that the `lsb_release` should be installed, therefore the command fails.
```
F_LOG "OS (lsb): $(lsb_release -a)"
```

I'll prepare PR with check if the tool is installed.

**Comment by phodina** [comment]
This issue is more for `lglaf` but the exception should be catched if there's no USB connected.
```
Traceback (most recent call last):
  File "/home/cylon2p0/programs/lglafng/lglaf.py", line 738, in <module>
    main()
  File "/home/cylon2p0/programs/lglafng/lglaf.py", line 694, in main
    comm = autodetect_device(args.cr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cylon2p0/programs/lglafng/lglaf.py", line 581, in autodetect_device
    return USBCommunication(cr)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/cylon2p0/programs/lglafng/lglaf.py", line 386, in __init__
    raise RuntimeError("USB device not found")
RuntimeError: USB device not found
```

Will also prepare PR to fix this issue.

**Comment by phodina** [comment]
@steadfasterX Is this the normal behavior to get this response to any command? I saw this also on other LG phone with Mediatek chipset.
```
Hello, I am LAF. Nice to meet you.
```

**Comment by phodina** [comment]
Seems most of the issues are connected to the `lglafng`. Should we discuss it here or in the repo for the tool?

**Comment by phodina** [comment]
Here's the `dmesg` from the LAF as all other commands see to be disabled.

[lm-g710-laf.log](https://github.com/steadfasterX/SALT/files/12352605/lm-g710-laf.log)


> @steadfasterX Is this the normal behavior to get this response to any command? I saw this also on other LG phone with Mediatek chipset.
> 
> ```
> Hello, I am LAF. Nice to meet you.
> ```

**Comment by steadfasterX** [comment]
> @steadfasterX Is this the normal behavior to get this response to any command? I saw this also on other LG phone with Mediatek chipset.
> 
> ```
> Hello, I am LAF. Nice to meet you.
> ```

see: https://github.com/steadfasterX/lglaf/issues/14#issuecomment-1671725947

**Comment by steadfasterX** [comment]
> This issue is more for `lglaf` but the exception should be catched if there's no USB connected.
> 
> ```
> Traceback (most recent call last):
>   File "/home/cylon2p0/programs/lglafng/lglaf.py", line 738, in <module>
>     main()
>   File "/home/cylon2p0/programs/lglafng/lglaf.py", line 694, in main
>     comm = autodetect_device(args.cr)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/cylon2p0/programs/lglafng/lglaf.py", line 581, in autodetect_device
>     return USBCommunication(cr)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "/home/cylon2p0/programs/lglafng/lglaf.py", line 386, in __init__
>     raise RuntimeError("USB device not found")
> RuntimeError: USB device not found
> ```
> 
> Will also prepare PR to fix this issue.

that must be handled in the lglaf repo not here
